### PR TITLE
consistent language: removed "we", "you" and past tense

### PR DESCRIPTION
**Pull request by tuzov**
improving language consistency

### CODE REVIEW

**Comment by blankdots** [comment]
we need to make the changes in the `sensitive-data-archive` repo see which file are imported from there: https://github.com/neicnordic/neic-sda/blob/master/aggregate-mappings.json

**Comment by tuzov** [comment]
made a PR in the main repo: https://github.com/neicnordic/sensitive-data-archive/pull/556

**Comment by lilachic** [comment]
Minor thing, there are still left a few "we" expressions that could be replaced by passive tense: index.md line 48. deploy-k8s.md line 70 and trobleshooting.md lines 3 and 61.

**Comment by tuzov** [comment]
@lilachic thank you for pointing out! fixed now

**Review by blankdots — APPROVED** [review]

**Comment by blankdots** [comment]
@tuzov seems some conflicts with wordlist need resolving, but other than that looks good

**Review by blankdots — APPROVED** [review]

**Review by aaperis — APPROVED** [review]

**Pull request merged**
